import { LOADING, SAVE_PROJECT, UPDATE_PROJECT, UPDATE_LOADING } from "../actions/types"

const initialstate = {
    isFetching: false,
    // dummy data
    teamMembers: [
        { label: "Sarah Conners", value: "Sarah Conners" },
        { label: "Mike Smith", value: "Mike Smith" },
        { label: "Wally Borg", value: "Wally Borg" },
        { label: "Cindy Lok", value: "Cindy Lok" },
        { label: "Kirk Wood", value: "Kirk Wood" },
        { label: "Laguna Wayward", value: "Laguna Wayward" },
    ],
    savedProjects: [
        {
            ProjectName: "Oakmont Management Group",
            totalSigners: 4,
            TeamMembers: [
                { label: "Sarah Conners", value: "Sarah Conners" },
                { label: "Mike Smith", value: "Mike Smith" },
                { label: "Wally Borg", value: "Whale" },
            ],
            AccountInfo: {
                Type: "Business",
                Ownership: "LLC",
                Benificiary: "",
                BeneficiaryDetails: "",
                totalSigners: 4,
                BusinessName: "Oakmont Management Group LLC",
                Prefix: "",
                PrefixName: "",
                PrefixEIN: "",
                AnotherName: "",
                Street: "123 Old Redwood Hwy Ste 200",
                City: "Windsor, CA 95492",
                EIN: "12-5682453",
                AccountType1: "OMG PAYROLL",
                AccountNumber1: "01-1002451-9",
            },
            signer1: {
                Name: "Kevin Tyler",
                Relationship: "Auth Signer/Control Party",
                Street: "572 James Ave",
                Position: "CFO & CIO",
                City: "Pacific Palisades, CA 90272",
                MailingStreet: "123 Main St Ste 1200",
                MailingCity: "Irvine, CA 92614",
                PrimaryIDType: "Drivers License",
                Number: "F1234576 CA",
                IssueDate1: "01/26/2017",
                ExpirationDate1: "01/19/2022",
                OtherID: "Passport",
                OtherDesc: "Passport",
                Expires: "09/26/2021",
                Employer: "Oakmont Management Group",
                Title: "CFO",
                email: "ktyler@email.com",
                WorkPhone: "",
                HomePhone: "",
                Cell: "(123) 456-4567",
                DOB: "01/19/1981",
                SSN: "123-45-6789",
            },
            signer2: {
                Name: "Jimmy Neutron",
                Relationship: "Auth Signer/Control Party",
                Street: "123 Lucero Ave",
                Position: "President",
                City: "Pacific Palisades, CA 90272",
                MailingStreet: "123 Main St Ste 1200",
                MailingCity: "Irvine, CA 92614",
                PrimaryIDType: "Drivers License",
                Number: "F1234576 CA",
                IssueDate1: "01/26/2017",
                ExpirationDate1: "01/19/2022",
                OtherID: "Passport",
                OtherDesc: "Passport",
                Expires: "09/26/2021",
                Employer: "Oakmont Management Group",
                Title: "CFO",
                email: "jneutron@email.com",
                WorkPhone: "",
                HomePhone: "",
                Cell: "(123) 456-4567",
                DOB: "01/19/1981",
                SSN: "123-45-6789",
            },
            signer3: {
                Name: "Matthew Stevenson",
                Relationship: "Authorized Signer",
                Street: "12436 Gold Dr",
                Position: "COO",
                City: "Rancho Cucamonga, CA 91739",
                MailingStreet: "123 Main St Ste 1200",
                MailingCity: "Irvine, CA 92614",
                PrimaryIDType: "Drivers License",
                Number: "B1234568 CA",
                IssueDate1: "03/02/2020",
                ExpirationDate1: "01/20/2025",
                OtherID: "Passport",
                OtherDesc: "Passport",
                Expires: "09/26/2021",
                Employer: "Oakmont Management Group",
                Title: "COO",
                email: "matt.stevenson@email.com",
                WorkPhone: "",
                HomePhone: "",
                Cell: "(123) 456-7535",
                DOB: "01/20/1981",
                SSN: "123-45-4567",
            },
            signer4: {
                Name: "James Nicholas Meek",
                Relationship: "Authorized Signer",
                Street: "111 Spring Harbor",
                Position: "COO",
                City: "Aliso Viejo, CA 92656",
                MailingStreet: "",
                MailingCity: "",
                PrimaryIDType: "Drivers License",
                Number: "D1234689 CA",
                IssueDate1: "04/27/2020",
                ExpirationDate1: "06/17/2025",
                OtherID: "Credit Card",
                OtherDesc: "Visa",
                Expires: "05/30/2025",
                Employer: "Oakmont Management Group",
                Title: "Controller",
                email: "jmeek@email.com",
                WorkPhone: "",
                HomePhone: "",
                Cell: "(123) 456-7896",
                DOB: "06/17/1982",
                SSN: "123-58-5465",
            },
        },
    ],
    Completed: [
        {
            ProjectName: "Nordby Construction Company",
            totalSigners: 2,
            TeamMembers: [
                { label: "Sarah Conners", value: "Sarah Conners" },
                { label: "Mike Smith", value: "Mike Smith" },
            ],
            AccountInfo: {
                Type: "Business",
                Ownership: "LLC",
                Benificiary: "",
                BeneficiaryDetails: "",
                totalSigners: 4,
                BusinessName: "Nordby Construction Company",
                Prefix: "",
                PrefixName: "",
                PrefixEIN: "",
                AnotherName: "",
                Street: "123 Old Redwood Hwy Ste 200",
                City: "Windsor, CA 95492",
                EIN: "12-1228206",
                AccountType1: "OMG PAYROLL",
                AccountNumber1: "01-1002451-9",
            },
            signer1: {
                Name: "Kevin Tyler",
                Relationship: "Auth Signer/Control Party",
                Street: "572 James Ave",
                Position: "CFO & CIO",
                City: "Pacific Palisades, CA 90272",
                MailingStreet: "123 Main St Ste 1200",
                MailingCity: "Irvine, CA 92614",
                PrimaryIDType: "Drivers License",
                Number: "F1234576 CA",
                IssueDate1: "01/26/2017",
                ExpirationDate1: "01/19/2022",
                OtherID: "Passport",
                OtherDesc: "Passport",
                Expires: "09/26/2021",
                Employer: "Oakmont Management Group",
                Title: "CFO",
                email: "ktyler@email.com",
                WorkPhone: "",
                HomePhone: "",
                Cell: "(123) 456-4567",
                DOB: "01/19/1981",
                SSN: "123-45-6789",
            },
            signer2: {
                Name: "Jimmy Neutron",
                Relationship: "Auth Signer/Control Party",
                Street: "123 Lucero Ave",
                Position: "President",
                City: "Pacific Palisades, CA 90272",
                MailingStreet: "123 Main St Ste 1200",
                MailingCity: "Irvine, CA 92614",
                PrimaryIDType: "Drivers License",
                Number: "F1234576 CA",
                IssueDate1: "01/26/2017",
                ExpirationDate1: "01/19/2022",
                OtherID: "Passport",
                OtherDesc: "Passport",
                Expires: "09/26/2021",
                Employer: "Oakmont Management Group",
                Title: "CFO",
                email: "jneutron@email.com",
                WorkPhone: "",
                HomePhone: "",
                Cell: "(123) 456-4567",
                DOB: "01/19/1981",
                SSN: "123-45-6789",
            },
        },
    ],
}

export const reducer = (state = initialstate, action) => {
    switch (action.type) {
        case LOADING:
            return Object.assign({}, state, {
                // toggles loading and sends value back to component
                isFetching: true,
            })
        case UPDATE_LOADING:
            return Object.assign({}, state, {
                // toggles loading and sends value back to component
                isFetching: false,
            })
        case SAVE_PROJECT:
            state.savedProjects.push(action.payload)
            return { ...state, }
        case UPDATE_PROJECT:
            state.savedProjects[action.payload.ProjectName] = action.payload
            return {
                ...state,
            }
        default:
            return state
    }
}
